GRANT ALL PRIVILEGES ON DATABASE "${env:POSTGRESQL_DATABASE_NAME}" TO "${env:SERVICE_API_IDENTITY_PRINCIPAL_NAME}";
GRANT USAGE ON SCHEMA public TO "${env:SERVICE_API_IDENTITY_PRINCIPAL_NAME}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${env:SERVICE_API_IDENTITY_PRINCIPAL_NAME}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${env:SERVICE_API_IDENTITY_PRINCIPAL_NAME}";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${env:SERVICE_API_IDENTITY_PRINCIPAL_NAME}";