name: react-app
metadata:
  subscription: ${AZURE_SUBSCRIPTION_ID}
  location: ${AZURE_LOCATION}

infra:
  bicep: ./infra/main.bicep

hooks:
  postprovision:
    shell: pwsh
    continueOnError: false
    interactive: true
    run: ./azd-hooks/postprovision.ps1
    env:
      SERVICE_API_IDENTITY_PRINCIPAL_NAME: ${SERVICE_API_IDENTITY_PRINCIPAL_NAME}
      POSTGRESQL_SERVER_NAME: ${POSTGRESQL_SERVER_NAME}
      POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}

  postdeploy:
    shell: pwsh
    continueOnError: false
    interactive: true
    run: ./azd-hooks/postdeploy.ps1

services:
  UserPortal:
    project: ../../src/userportal
    host: containerapp
    language: js
    docker:
      context: ../../src/userportal
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
      path: DOCKERFILE
    dependsOn:
      - infra

  API:
    project: ../../src/api
    host: containerapp
    language: python
    docker:
      context: ../../src/api
      path: DOCKERFILE
      registry: ${AZURE_CONTAINER_REGISTRY_ENDPOINT}
    dependsOn:
      - infra
