
# Stage 1: Build the React app
FROM node:14 AS build
WORKDIR /app

ARG REACT_APP_SERVICE_API_ENDPOINT_URL

COPY . ./

# Create .env file with REACT_APP_SERVICE_API_ENDPOINT_URL
RUN echo "REACT_APP_SERVICE_API_ENDPOINT_URL: \"${REACT_APP_SERVICE_API_ENDPOINT_URL}\"" > ./.env

RUN npm install
RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
