
# Stage 1: Build the React app
FROM node:14 AS build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build


# Stage 2: Serve the React app with Nginx
FROM nginx:alpine

ARG SERVICE_API_ENDPOINT_URL
ENV REACT_APP_SERVICE_API_ENDPOINT_URL=${SERVICE_API_ENDPOINT_URL}

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]